### ISSUE TITLE
Replace IO with MonadBase IO wherever possible

### ISSUE THREAD

**Issue by k0ral** [willdonnelly/dyre#19]
Could you please use the more generic `MonadBase IO m => m a` type in place of `IO a` ?
Or at least `MonadIO m => m a` if you care about Haskell 98 compliance.

**Comment by frasertweedale** [comment]
I don't see much benefit for *dyre*, to be honest.  `MonadIO` is in *base* as of 4.9, but I still want to support 7.10 (*base-4.8*) and I don't think it's worth depending on *transformers* (small as it is) to perform this abstraction that is unlikely to benefit many people.

I'm going to close it, but feel free to reopen with a compelling example :)
