### ISSUE TITLE
Replace String with Data.Text

### ISSUE THREAD

**Issue by k0ral** [willdonnelly/dyre#20]
Could you please adapt the API to accept `Text` objects in place of `String` ones ?
Thank you.

**Comment by noughtmare** [comment]
Text is unnecessary in this package. The performance and memory usage improvement would be unnoticeable. This should wait until Data.Text is in base and the String/ByteString/Text problem is solved. See [this reddit thread] (https://www.reddit.com/r/haskell/comments/4p2vx7/what_can_i_do_to_help_the_stringbytestringtext/) for more info.

**Comment by k0ral** [comment]
Fair enough.
Just for the sake of clarification, it's not about performance/memory gains, it's about not punishing Data.Text users with extra boilerplate to convert String <=> Text.
Anyway, feel free to close this issue if it's not going to be handled any time soon.

**Comment by frasertweedale** [comment]
Most of the strings are just for command line arguments and similar.  I agree there is no benefit to changing to `Text`.  Closing the issue.
