### ISSUE TITLE
Dyre configuration file cannot find module

### ISSUE THREAD

**Issue by dmp1ce** [willdonnelly/dyre#26]
I'm using a basic cabal executable configuration. My project is just a DyreExample. Every time I run the executable I get this error when the configuration file is found. I'm running the executable with `cabal run`.

```
  Could not find module ‘MyModule’                                                                                         
  Use -v to see a list of the files searched for.
```

Why can't Dyre find my module which is defined in cabal and is compiled into the executable?

**Comment by dmp1ce** [comment]
I guess my question could also be, how can I get Dyre to work with a simple cabal executable so that the configuration can access the executable modules?

**Comment by dmp1ce** [comment]
I'm still trying to figure this one out. I created an example Cabal project to better explain what I'm seeing. 

https://github.com/dmp1ce/dyreExampleCabal

**Comment by saep** [comment]
You have to export the module `DyreExample` in a library and `cabal install` that library if you want to use it that way. That does not really have anything to do with dyre.

**Comment by dmp1ce** [comment]
Apparently I don't know enough about Cabal to get Dyre working with an executable. I'm trying to create a library in cabal that is referenced from an executable but I'm getting build errors. Thanks for your help.

**Comment by dmp1ce** [comment]
I actually did get this to work and after I ran `cabal install` the code worked as you said. I am still wondering if it is possible to use Dyre in only an executable, without an additional library, in Cabal.
