### ISSUE TITLE
Include dyre in stackage

### ISSUE THREAD

**Issue by saep** [willdonnelly/dyre#27]
One of my mid-term goals is to put my [neovim plugin provider](https://github.com/saep/nvim-hs) on stackage. Your package is the only one keeping me from doing so and I really need this way of recompilation. 

Would you mind putting it there? If you don't want to do the work, I can to it.

**Comment by noughtmare** [comment]
This has been solved now, right?

**Comment by saep** [comment]
Haven't noticed that it is on stackage. So, yes it has been solved.
