### ISSUE TITLE
'errors.log' is kept after configuration file removal

### ISSUE THREAD

**Issue by dan-t** [willdonnelly/dyre#35]
Hi,

if a configuration file couldn't be build then an `errors.log` file is created and its content is forwarded to the application using `dyre`.

If the configuration file gets deleted then the `errors.log` file seems to be kept and  continually forwarded to the application.

Greetings,
Daniel

**Comment by dan-t** [comment]
Sorry, there's already the same issue (https://github.com/willdonnelly/dyre/issues/10).

**Comment by frasertweedale** [comment]
Actually this was *not* the same issue as #10.  But it has was fixed in 5e6a233eac037b586ebaaa2f30760f6a19adb251 and will be included in the next release.
