### ISSUE TITLE
Add the config dir to the include list to permit other modules.

### ISSUE THREAD

**Issue by LeifW** [willdonnelly/dyre#36]
I don't necessarily want all of my config in a single file. But if I factor out parts into other modules, my config won't re-compile unless I run the program from in the `$HOME/.config/programName` directory, because the `includeCurrentDirectory` setting defaults to true. More useful to me would be adding `System.Environment.XDG.BaseDir.getUserConfigDir programName` as a `-i` argument to the ghc execution.

**Comment by frasertweedale** [comment]
I understand the want, but it's a bit tricky.  Right now, we only need to check the timestamp of a single file (the custom config).  If we add config dir to module path we have to check - recursively - all Haskell files contained therein.

Therefore I'm inclined to close this issue WONTFIX.  But I will wait for feedback from you @LeifW (or others) before deciding.

**Comment by LeifW** [comment]
Sorry, I wasn't really asking for another file to be watched, merely for another directory to be added to include dirs. Currently, if you include something from another file in your config, you must either compile the file yourself with an -i arg passed to GHC, or, using dyre with includeCurrentDirectory set to true, run your dyre-enabled program from the same directory which has your extra module, or set a `-i` arg containing that directory in the `ghcOpts` of dyre.
The documentation for `includeCurrentDirectory`, "Whether to add current directory to include list", makes it sound like like dyre already passes a `-i` argument to GHC. I was just hoping to be able to use something besides $PWD for that, namely, `System.Environment.XDG.BaseDir.getUserConfigDir`.

**Comment by frasertweedale** [comment]
@LeifW that's correct, setting `includeCurrentDirectory` (which is `True` by default) does cause the current directory to be added to the GHC search path via `-i`.

But, I think this is a misfeature.  The point of dyre is to automatically reconfigure when it detects changed config.  But if you extract config out of `programName.hs` into modules, dyre *cannot detect changes to those modules*.  This is the case right now with `includeCurrentDirectory`.  I do not want to expand the misfeature.

Of course, I understand the desire to support modules.  But with dyre's current design, I can't see an obvious way to implement it that is robust and not excessively complex.

**Comment by LeifW** [comment]
Personally, I don't particularly care about detecting changes in other files, I just want it to be possible to use modules in my config, and detecting changes in the main config file is enough for me.
I mean, if I make cabal packages out of those other modules and install them, dyre isn't going to detect changes in them, either, but at least I can still compile my config with dyre.

**Comment by frasertweedale** [comment]
@LeifW hey so I discovered a thing.  *dyre* always adds `$confdir/lib/` to the GHC search path via `-i`.  Chuck your modules under `lib/` and you should have success.  Changes to files under `lib/` will trigger recompilation.

So I think I can close this as fixed? :)

**Comment by frasertweedale** [comment]
I will leave this open until I have documented the feature in the package haddock.
