### ISSUE TITLE
changes on custom configuration is detected but not on submodule

### ISSUE THREAD

**Issue by zoranbosnjak** [willdonnelly/dyre#37]
If I extend the basic example to use submodule, for example like this:

```haskell
-- ~/.config/dyreExample/dyreExample.hs
import DyreExample
import qualified MyModule
main = dyreExample $ defaultConfig { message = "Dyre Example v1.2", n = MyModule.random }
```

```haskell
-- ~/.config/dyreExample/MyModule.hs
module MyModule where
random :: Integer
random = 7
```

```haskell
-- DyreExample.hs
...
realMain Config{message = message, errorMsg = errorMsg, n = n} = do
...
    print n
...
    , Dyre.ghcOpts      = ["-i/path/to/.config/dyreExample"]
...
```

... then the change inside `MyModule.hs` is not detected and the custom configuration is not recompiled (for example if I change the value of `random`). It gets recompiled only after `~/.config/dyreExample/dyreExample.hs` is touched.

How can I workaround this problem?

**Comment by frasertweedale** [comment]
Put the module under `~/.config/dyreExample/lib/`.  That directory is always added to the search path.  See https://github.com/willdonnelly/dyre/issues/36 for more info.
