### ISSUE TITLE
Using dyre with any IO actions that need a config file written in Haskell

### ISSUE THREAD

**Issue by poscat0x04** [willdonnelly/dyre#38]
I think it's generally useful to parameterize the return type of realMain and warpMain to `IO a` as we might use dyre with any IO actions that need to load config files written in Haskell at runtime. Is it possible to do so or does dyre only works with the main function?

**Comment by frasertweedale** [comment]
It seems doable.  I'll have a stab at it soon.

**Comment by frasertweedale** [comment]
@poscat0x04 does https://github.com/willdonnelly/dyre/commit/f461359bab75fd21cafa386f8426613e1231be48 work for you?
