### ISSUE TITLE
Possible regression for Nix packages

### ISSUE THREAD

**Issue by romanofski** [willdonnelly/dyre#42]
I think the latest changes might have introduced a regression regarding builds with the Nix package manager. I have not had a chance to look at builds in Fedora. I currently don't have any specifics, just symptoms.

Typical problem is, that the packages can't be picked up (Note: this includes printing the flags I changed myself):
```
% result/bin/purebred                                                            
Configuration '/home/rjoost/.config/purebred/purebred.hs' changed. Recompiling.
Flags: -v0-i/home/rjoost/.config/purebred/lib-i/home/rjoost/works/purebred-i/nix/store/y5g5s6q926lsj6h9dyjgpdq91h3bwhzr-purebred-0.1.0.0/lib/ghc-8.8.4/x86_64-linux-ghc-8.8.4/purebred-0.1.0.0-7Yxwc0odFxzINrVJ1QtwAR-threaded--make/home/rjoost/.config/purebred/purebred.hs-ou
tputdir/home/rjoost/.cache/purebred-o/home/rjoost/.cache/purebred/purebred-linux-x86_64.tmp-fforce-recomp
Error occurred while loading configuration file.
purebred: 
/home/rjoost/.config/purebred/purebred.hs:24:1: error:
    Could not find module ‘Purebred’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
24 | import Purebred
   | ^^^^^^^^^^^^^^^

/home/rjoost/.config/purebred/purebred.hs:25:1: error:
    Could not find module ‘Purebred.Plugin.ICU’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
25 | import qualified Purebred.Plugin.ICU
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/rjoost/.config/purebred/purebred.hs:33:1: error:
    Could not find module ‘Data.MIME’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
33 | import Data.MIME (matchContentType)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

CallStack (from HasCallStack):
  error, called at src/Purebred.hs:347:69 in purebred-0.1.0.0-7Yxwc0odFxzINrVJ1QtwAR:Purebred
```

**Comment by romanofski** [comment]
First thing is, that nix creates a wrapper script around the actual executable:

```
 % cat result/bin/purebred
#! /nix/store/f7jzmxq9bpbxsg69cszx56mw14n115n5-bash-4.4-p23/bin/bash -e
export NIX_GHC='/nix/store/g221vbn7n6vl8gbd1ja2dvbxbrjlz7na-ghc-8.8.4-with-packages/bin/ghc'
exec "/nix/store/g221vbn7n6vl8gbd1ja2dvbxbrjlz7na-ghc-8.8.4-with-packages/bin/purebred"  "$@"
```

In dyre, the look up of the GHC executable works either if the `HC` environment variable is set or plain by using `ghc`. I don't know where we regressed here really. It will obviously work if the wrapper script would set the env variable to `HC`.

The above error happens, due to the fact that I ran this script in a mixed environment (Fedora with a nix installation). There `ghc` points to the system wide GHC variable.

**Comment by romanofski** [comment]
Alright I checked on NixOS to see what is happening here:

```
$ result/bin/purebred       
Configuration '/home/rjoost/.config/purebred/purebred.hs' changed. Recompiling.
purebred: ghc: runProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
Obviously here I don't have the misleading message, because there is no other GHC installation available.

**Comment by frasertweedale** [comment]
It seems like, at a minimum, we need to recognise `NIX_GHC`.  And that might just fix the issue entirely.

**Comment by romanofski** [comment]
Yep and changing the scripts environment variable from `NIX_GHC` to `HC` would compile the `purebred` obviously. What I'm not so sure of is what made it work before.

**Comment by romanofski** [comment]
> It seems like, at a minimum, we need to recognise `NIX_GHC`. And that might just fix the issue entirely.

I wonder tho what made it work before. Dyre had no idea about the `NIX_GHC` environment variable, hadn't it?
