### ISSUE TITLE
Support for dynamic linking

### ISSUE THREAD

**Issue by reinerp** [willdonnelly/dyre#5]
GHC's `-dynamic` flag (see http://www.haskell.org/ghc/docs/latest/html/users_guide/options-phases.html#options-linker) can improve link times, which can be quite useful for dynamic reconfigurations, as the configuration file is typically much smaller than the library it is linking to.

It would be good to support dynamic linking in Dyre. Not all users will want this (for instance, it isn't supported in Windows, and it requires the relevant packages to have been installed with @--enable-shared@), so there should be some way for the user to enable/disable dynamic linking. The easiest way I see is to add a `--dynamic-linking` commandline option which enables dynamic linking in GHC.

**Comment by frasertweedale** [comment]
I agree it can be left to application to configure dyre with `Dyre.Config.defaultConfig {ghcOpts = ["-dynamic"]}`.  If you disagree or you can explain a use case that requires more, please reopen and provide details.
